on:
  schedule:
    - cron: '0 0 * * *'  # Runs at midnight UTC every day
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r src/requirements.txt

      - name: Install necessary LaTeX packages
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-latex-base texlive-fonts-recommended texlive-fonts-extra texlive-latex-extra

      - name: Run data pipeline
        env:
          FRED_API_KEY: ${{ secrets.FRED_API_KEY }}
        run: |
          python src/update_data.py

      - name: Generate website
        run: |
          python src/generate_site.py

      - name: Update README with last update time
        run: |
          sed -i "/^Last run:/c\Last run: $(date -u)" README.md

      - name: Configure Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Add changes
        run: |
          git add .

      - name: Commit changes
        run: |
          git commit -m "Automated update of data and website"

      - name: Push changes
        run: |
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
