name: Update README on Commit

on:
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Calculate time left before next scheduled run
        id: time-left
        run: |
          current_time=$(date -u +%s)
          next_run=$(date -u -d "00:00 tomorrow" +%s)
          time_left=$((next_run - current_time))
          hours_left=$((time_left / 3600))
          minutes_left=$(((time_left % 3600) / 60))
          echo "TIME_LEFT=${hours_left}h ${minutes_left}m" >> $GITHUB_ENV

      - name: Update README with time left
        run: |
          sed -i '/^Time left before next scheduled run:/c\Time left before next scheduled run: ${{ env.TIME_LEFT }}' README.md

      - name: Configure Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Add changes
        run: |
          git add README.md

      - name: Commit changes
        run: |
          git commit -m "Update README with time left before next scheduled run" || echo "No changes to commit"

      - name: Push changes
        run: |
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
